Fix php8 warnings
BeAPI/shoppingfeed-advanced pull request #2
Opened 2022-08-23 12:56 UTC by f2cmbeapi

2022-08-25 12:10 UTC, petitphp requested changes

2022-08-25 12:10 UTC, petitphp commented on shoppingfeed-advanced.php
> + * Version:                       6.1.0
Il ne faut pas modifier la version du plugin ici. La version du plugin est modifier uniquement lorsque l'on fait une release du plugin.

2022-08-25 12:21 UTC, f2cmbeapi commented on shoppingfeed-advanced.php
> + * Version:                       6.1.0
Corrigé

2022-08-25 12:28 UTC, petitphp commented on shoppingfeed-advanced.php
> + * Version:                       6.1.0
Merci !

2022-08-26 12:59 UTC, petitphp approved these changes

2022-08-26 12:59 UTC, merged